/abolish

CREATE TABLE CLIENTES (
  DNI    VARCHAR(9),
  NOMBRE VARCHAR(20),
  DIR    VARCHAR(30),
  PRIMARY KEY (DNI)
);
  
CREATE TABLE SUCURSALES (
  NSUC   VARCHAR(4),
  CIUDAD VARCHAR(30),
  PRIMARY KEY (NSUC)
);
  
CREATE TABLE CUENTAS (
  COD     VARCHAR(4) NOT NULL,
  DNI     VARCHAR(9) NOT NULL,
  NSUCURS VARCHAR(4) NOT NULL,
  SALDO   INT DEFAULT 0 CHECK(SALDO>=0),
  PRIMARY KEY (COD, DNI, NSUCURS),
  FOREIGN KEY (DNI) REFERENCES CLIENTES (DNI),
  FOREIGN KEY (NSUCURS) REFERENCES SUCURSALES (NSUC)
);
  

  