/p Empleados
/display_answer on
/duplicates on

SELECT DEPTNO, DEPTNAME, ADMRDEPT
FROM DEPARTMENT;

SELECT ADMRDEPT
FROM DEPARTMENT;

SELECT ALL ADMRDEPT
FROM DEPARTMENT;

SELECT DISTINCT ADMRDEPT
FROM DEPARTMENT;

SELECT DISTINCT WORKDEPT, JOB
FROM EMPLOYEE;

SELECT WORKDEPT, JOB
FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT DEPTNO, DEPTNAME, ADMRDEPT
FROM DEPARTMENT
ORDER BY ADMRDEPT ASC;

SELECT ADMRDEPT, DEPTNAME, DEPTNO
FROM DEPARTMENT
ORDER BY ADMRDEPT ASC, DEPTNO DESC;

SELECT DEPTNO, ADMRDEPT
FROM DEPARTMENT
WHERE ADMRDEPT='A00';

SELECT LASTNAME, EDLEVEL
FROM EMPLOYEE
WHERE EDLEVEL >= 19;

SELECT EMPNO, LASTNAME, BIRTHDATE
FROM EMPLOYEE
WHERE BIRTHDATE >= DATE '1985-01-01'
ORDER BY BIRTHDATE;

SELECT EMPNO, JOB, EDLEVEL
FROM EMPLOYEE
WHERE JOB='ANALYST' AND EDLEVEL=20;

SELECT EMPNO, JOB, EDLEVEL
FROM EMPLOYEE
WHERE (JOB='ANALYST' AND EDLEVEL=16)
OR EDLEVEL=18
ORDER BY JOB, EDLEVEL;

SELECT EMPNO, EDLEVEL
FROM EMPLOYEE
WHERE EDLEVEL BETWEEN 12 AND 15
ORDER BY EDLEVEL;

SELECT LASTNAME, EDLEVEL
FROM EMPLOYEE
WHERE EDLEVEL IN (14, 19, 20)
ORDER BY EDLEVEL, LASTNAME;

SELECT LASTNAME
FROM EMPLOYEE
WHERE LASTNAME LIKE 'G%';

SELECT LASTNAME
FROM EMPLOYEE
WHERE LASTNAME LIKE '%SON';

SELECT LASTNAME
FROM EMPLOYEE
WHERE LASTNAME LIKE '%M%N%';

SELECT LASTNAME
FROM EMPLOYEE
WHERE LASTNAME LIKE '_C%';

SELECT DEPTNO, DEPTNAME
FROM DEPARTMENT
WHERE DEPTNO NOT LIKE 'D%';

SELECT EMPNO, SALARY, SALARY*1.0375
FROM EMPLOYEE
WHERE SALARY < 200000
ORDER BY EMPNO;

SELECT EMPNO, SALARY, (BONUS/SALARY)*100 AS PERCENTAGE
FROM EMPLOYEE
WHERE (BONUS/SALARY)*100 > 4
ORDER BY EMPNO;

SELECT EMPNO, SALARY, TRUNC(SALARY*1.0375, 2)
FROM EMPLOYEE
ORDER BY EMPNO;

SELECT LASTNAME + ',' + FIRSTNAME AS FULLNAME
FROM EMPLOYEE
WHERE WORKDEPT = 'A00'
ORDER BY FULLNAME;

SELECT DEPTNO FROM DEPARTMENT
UNION
SELECT WORKDEPT FROM EMPLOYEE;

SELECT DEPTNO FROM DEPARTMENT;

SELECT DISTINCT WORKDEPT FROM EMPLOYEE;

